In [1]:
import numpy as np
arr = np.zeros(shape = (3,4,8))+5
arr*2

array([[[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]],

       [[10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.],
        [10., 10., 10., 10., 10., 10., 10., 10.]]])

In [3]:
arr1 = np.linspace(4,8,80,endpoint = True,dtype = float)
arr1

array([4.        , 4.05063291, 4.10126582, 4.15189873, 4.20253165,
       4.25316456, 4.30379747, 4.35443038, 4.40506329, 4.4556962 ,
       4.50632911, 4.55696203, 4.60759494, 4.65822785, 4.70886076,
       4.75949367, 4.81012658, 4.86075949, 4.91139241, 4.96202532,
       5.01265823, 5.06329114, 5.11392405, 5.16455696, 5.21518987,
       5.26582278, 5.3164557 , 5.36708861, 5.41772152, 5.46835443,
       5.51898734, 5.56962025, 5.62025316, 5.67088608, 5.72151899,
       5.7721519 , 5.82278481, 5.87341772, 5.92405063, 5.97468354,
       6.02531646, 6.07594937, 6.12658228, 6.17721519, 6.2278481 ,
       6.27848101, 6.32911392, 6.37974684, 6.43037975, 6.48101266,
       6.53164557, 6.58227848, 6.63291139, 6.6835443 , 6.73417722,
       6.78481013, 6.83544304, 6.88607595, 6.93670886, 6.98734177,
       7.03797468, 7.08860759, 7.13924051, 7.18987342, 7.24050633,
       7.29113924, 7.34177215, 7.39240506, 7.44303797, 7.49367089,
       7.5443038 , 7.59493671, 7.64556962, 7.69620253, 7.74683

In [7]:
np.matrix([[1,2,3,4,5,6],[3,4,5,6,6,7]])

matrix([[1, 2, 3, 4, 5, 6],
        [3, 4, 5, 6, 6, 7]])

In [13]:
arr2 = np.ones((4,5,2))
np.ndim(arr2)
np.shape(arr2)
np.size(arr2)


40

In [18]:
x1 = np.random.randn(3,3,3)
x2 = np.random.randn(3,3,3)
x2+x1

array([[[ 0.02939944,  1.24128538, -1.52369742],
        [-0.56290308, -2.18541391,  1.56231244],
        [-0.70918718,  2.60965064,  0.79632135]],

       [[ 1.47137303,  0.30747294,  2.81280045],
        [ 1.57821796,  0.32804275,  0.46026868],
        [-0.95358682,  0.900333  ,  1.17805092]],

       [[ 1.03288848, -1.4880197 , -1.56974178],
        [-0.01397281,  0.90200273,  0.34541667],
        [-0.63777214, -3.92529156,  1.10183961]]])

In [21]:
rand_arr = np.random.randint(2,200,(3,5,3))
rand_arr

array([[[139, 160,  23],
        [160,  80, 165],
        [193, 110, 145],
        [ 62, 130,  73],
        [ 20, 139, 133]],

       [[198, 122,   5],
        [ 11,  79, 111],
        [ 40,  75, 133],
        [ 37, 132, 177],
        [ 42,  32,  89]],

       [[ 61,  64, 183],
        [ 28, 178,  27],
        [157, 116,  85],
        [  7,  38, 119],
        [192, 157,  12]]])

In [34]:
rand_arr[:,[0,1]]

array([[[139, 160,  23],
        [160,  80, 165]],

       [[198, 122,   5],
        [ 11,  79, 111]],

       [[ 61,  64, 183],
        [ 28, 178,  27]]])

In [18]:
np.ndarray(9).cumsum().reshape(3,3)

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 5.61258574e-321],
       [6.01346930e-154, 1.80404079e-153, 6.98346901e-077]])